package com.gmail.volodymyrdotsenko.cms.fe.vaadin.views.administration;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.InlineDateField;

public class UserManagementMainComp extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private InlineDateField inlineDateField_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UserManagementMainComp() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		System.out.println("UserManagementMainComp");
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(true);
		mainLayout.setWidth("100%");
		mainLayout.setHeight(300, Unit.PIXELS);
	
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// inlineDateField_1
		inlineDateField_1 = new InlineDateField();
		inlineDateField_1.setImmediate(false);
		inlineDateField_1.setWidth("-1px");
		inlineDateField_1.setHeight("-1px");	
		mainLayout.addComponent(inlineDateField_1);
		
		return mainLayout;
	}
}
