package com.gmail.volodymyrdotsenko.vaadindemo;

import org.springframework.beans.factory.annotation.Autowired;

import com.gmail.volodymyrdotsenko.vaadindemo.spring.beans.UtilsBean;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.spring.annotation.SpringUI;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.LoginForm;

@SpringUI
public class SimpleComp extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private LoginForm loginForm_1;

	private UtilsBean util;

	public void setUtil(UtilsBean util) {
		this.util = util;
	}

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public SimpleComp() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here

		loginForm_1.addLoginListener(e -> {
			System.out.println(e.getLoginParameter("password"));
			System.out.println(util.getVersion());
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1, "right:0.0px;bottom:0.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(3);
		gridLayout_1.setRows(3);

		// loginForm_1
		loginForm_1 = new LoginForm();
		loginForm_1.setStyleName("v-loginform");
		loginForm_1.setImmediate(false);
		loginForm_1.setWidth("-1px");
		loginForm_1.setHeight("205px");
		gridLayout_1.addComponent(loginForm_1, 1, 1);
		gridLayout_1.setComponentAlignment(loginForm_1, new Alignment(48));

		return gridLayout_1;
	}

}
